### ISSUE TITLE
Use stardist segmentation for ellipsoid fitting

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon-ellipsoid-fitting#8]

**Comment by stefanhahmann** [comment]
# User story

The current implementation of ellipsoid fitting is rather slow (~5 hours for 500.000 spots) and also imprecise. Both is unsatisfiable for a user who wants to run it. Thus, it would be nice, if the ellipsoid fitting could exploit the GPU, if an NVIDIA graphics card is available. I would be desirable to achieve higher performance and more precise results.

# Acceptance criteria

* Additional Ellipsoid fitting option that
  * uses JDLL: https://github.com/bioimage-io/JDLL
  * cuda: https://developer.nvidia.com/cuda-toolkit
  * cuDNN: https://developer.nvidia.com/cudnn
* Runs significantly faster than current ellipsoid fitting when performed on GPU
* Exploits stardist segmentation algorithms - https://github.com/stardist/stardist

# Tasks

- [x] Prototypical testing by https://github.com/Noam-Dori
  - [x] Load resulting code into project - cf.: [stardist_test.zip](https://github.com/mastodon-sc/mastodon-ellipsoid-fitting/files/12336723/stardist_test.zip)
- [x] Install GPU drivers
  - [x] Install cuda (https://developer.nvidia.com/cuda-toolkit)
  - [x] Install cuDNN (https://developer.nvidia.com/cudnn)
- [x] One time procedure: download tensorflow engine via the outcommented code
- [x] Adapth paths to file system
- [x] Test, if the code runs stabily (multiple times). On the machine of https://github.com/Noam-Dori the segmentation crashed sometimes
- [ ] Partion/crop images before handing them over to prediction. A GPU memory error occurs, if one complete timepoint is processed by stardist at the same time. Partioning and cropping may solve this.
- [ ] Filter StarDist results. In the StarDist 2D ImageJ plugin, there is some post-processing of StarDist results (i.e. non-maximum suppression), which does not exist in the 3D translation and results in too many segments.
- [ ] Integrate loop for multiple timepoints
- [ ] Handle the disk leak C:\User\AppData\Local\Temp\tensorflow_* -> delete those files after running (it is a downloaded library from online used in processing)
- [ ] Add method to derive variance/covariance params from set of Pixels, cf.: https://github.com/mastodon-sc/mastodon-ellipsoid-fitting/pull/9
- [ ]  Integrate that into the plugin

# Additional information
- StarDist publicly available training+test data: https://github.com/stardist/stardist/releases/download/0.3.0/demo3D.zip
  - Timelapse with 27 timepoints as HDF5 dataset: 
[stardist.zip](https://github.com/mastodon-sc/mastodon-ellipsoid-fitting/files/12337057/stardist.zip)

- StarDist3D model to be used with JDLL: [adapted_stardist_model.zip](https://github.com/mastodon-sc/mastodon-ellipsoid-fitting/files/12336885/adapted_stardist_model.zip)
  - Model has been translated from pre-trained StarDist Model (contained here: https://github.com/stardist/stardist/releases/download/0.3.0/demo3D.zip)  using this Python script: [convert_stardist_h5_to_pb.zip](https://github.com/mastodon-sc/mastodon-ellipsoid-fitting/files/12337048/convert_stardist_h5_to_pb.zip)
